# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 893)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setMaximumSize(QtCore.QSize(50, 100))
        self.returnButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.returnButton.setStyleSheet("image: url(:/return-icon/returnIcon.jpg);\n"
"background-image: url(:/return-icon/returnIcon.jpg);")
        self.returnButton.setText("")
        self.returnButton.setObjectName("returnButton")
        self.gridLayout_2.addWidget(self.returnButton, 0, 0, 1, 1)
        self.mainMenu = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainMenu.setStyleSheet("alternate-background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(255, 176, 176, 167), stop:0.3 rgba(255, 151, 151, 92), stop:0.4 rgba(255, 125, 125, 51), stop:0.5 rgba(255, 76, 76, 205), stop:0.52 rgba(255, 76, 76, 205), stop:0.6 rgba(255, 180, 180, 84), stop:1 rgba(255, 255, 255, 0));")
        self.mainMenu.setObjectName("mainMenu")
        self.firstPage = QtWidgets.QWidget()
        self.firstPage.setObjectName("firstPage")
        self.gridLayout = QtWidgets.QGridLayout(self.firstPage)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.firstPage)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 650))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.primerOrden = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.primerOrden.setFont(font)
        self.primerOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.primerOrden.setStyleSheet("\n"
"")
        self.primerOrden.setObjectName("primerOrden")
        self.segundoOrden = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.segundoOrden.setFont(font)
        self.segundoOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.segundoOrden.setObjectName("segundoOrden")
        self.gridLayout_18.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.mainMenu.addWidget(self.firstPage)
        self.primerOrdenMenu = QtWidgets.QWidget()
        self.primerOrdenMenu.setObjectName("primerOrdenMenu")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.primerOrdenMenu)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.primerOrdenMenu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMaximumSize(QtCore.QSize(200, 20))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.frecPrimerOrden = QtWidgets.QLineEdit(self.frame_6)
        self.frecPrimerOrden.setEnabled(True)
        self.frecPrimerOrden.setMinimumSize(QtCore.QSize(220, 0))
        self.frecPrimerOrden.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frecPrimerOrden.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.frecPrimerOrden.setInputMask("")
        self.frecPrimerOrden.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.frecPrimerOrden.setClearButtonEnabled(True)
        self.frecPrimerOrden.setObjectName("frecPrimerOrden")
        self.horizontalLayout_4.addWidget(self.frecPrimerOrden)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.gananciaPrimerOrden = QtWidgets.QLineEdit(self.frame_6)
        self.gananciaPrimerOrden.setMinimumSize(QtCore.QSize(220, 0))
        self.gananciaPrimerOrden.setMaximumSize(QtCore.QSize(220, 16777215))
        self.gananciaPrimerOrden.setPlaceholderText("")
        self.gananciaPrimerOrden.setClearButtonEnabled(True)
        self.gananciaPrimerOrden.setObjectName("gananciaPrimerOrden")
        self.horizontalLayout_2.addWidget(self.gananciaPrimerOrden)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 1, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 2, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(314, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(314, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pasaAltosPrimerOrden = QtWidgets.QPushButton(self.frame_4)
        self.pasaAltosPrimerOrden.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaAltosPrimerOrden.setFont(font)
        self.pasaAltosPrimerOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaAltosPrimerOrden.setObjectName("pasaAltosPrimerOrden")
        self.verticalLayout.addWidget(self.pasaAltosPrimerOrden)
        self.pasaBajosPrimerOrden = QtWidgets.QPushButton(self.frame_4)
        self.pasaBajosPrimerOrden.setMaximumSize(QtCore.QSize(10000, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaBajosPrimerOrden.setFont(font)
        self.pasaBajosPrimerOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaBajosPrimerOrden.setObjectName("pasaBajosPrimerOrden")
        self.verticalLayout.addWidget(self.pasaBajosPrimerOrden)
        self.pasaTodoPrimerOrden = QtWidgets.QPushButton(self.frame_4)
        self.pasaTodoPrimerOrden.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaTodoPrimerOrden.setFont(font)
        self.pasaTodoPrimerOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaTodoPrimerOrden.setObjectName("pasaTodoPrimerOrden")
        self.verticalLayout.addWidget(self.pasaTodoPrimerOrden)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.gridLayout_7.addWidget(self.frame_2, 0, 0, 1, 1)
        self.mainMenu.addWidget(self.primerOrdenMenu)
        self.segundoOrdenMenu = QtWidgets.QWidget()
        self.segundoOrdenMenu.setObjectName("segundoOrdenMenu")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.segundoOrdenMenu)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.segundoOrdenMenu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pasaAltosSegundoOrden = QtWidgets.QPushButton(self.frame_8)
        self.pasaAltosSegundoOrden.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaAltosSegundoOrden.setFont(font)
        self.pasaAltosSegundoOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaAltosSegundoOrden.setObjectName("pasaAltosSegundoOrden")
        self.verticalLayout_4.addWidget(self.pasaAltosSegundoOrden)
        self.pasaBajosSegundoOrden = QtWidgets.QPushButton(self.frame_8)
        self.pasaBajosSegundoOrden.setMaximumSize(QtCore.QSize(10000, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaBajosSegundoOrden.setFont(font)
        self.pasaBajosSegundoOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaBajosSegundoOrden.setObjectName("pasaBajosSegundoOrden")
        self.verticalLayout_4.addWidget(self.pasaBajosSegundoOrden)
        self.pasaBanda = QtWidgets.QPushButton(self.frame_8)
        self.pasaBanda.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaBanda.setFont(font)
        self.pasaBanda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaBanda.setObjectName("pasaBanda")
        self.verticalLayout_4.addWidget(self.pasaBanda)
        self.pasaTodoSegundoOrden = QtWidgets.QPushButton(self.frame_8)
        self.pasaTodoSegundoOrden.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pasaTodoSegundoOrden.setFont(font)
        self.pasaTodoSegundoOrden.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pasaTodoSegundoOrden.setObjectName("pasaTodoSegundoOrden")
        self.verticalLayout_4.addWidget(self.pasaTodoSegundoOrden)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.lowPassNotch = QtWidgets.QPushButton(self.frame_8)
        self.lowPassNotch.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lowPassNotch.setFont(font)
        self.lowPassNotch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lowPassNotch.setObjectName("lowPassNotch")
        self.gridLayout_6.addWidget(self.lowPassNotch, 2, 0, 1, 1)
        self.notch = QtWidgets.QPushButton(self.frame_8)
        self.notch.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.notch.setFont(font)
        self.notch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notch.setAutoFillBackground(False)
        self.notch.setStyleSheet("")
        self.notch.setObjectName("notch")
        self.gridLayout_6.addWidget(self.notch, 1, 0, 1, 1)
        self.highPassNotch = QtWidgets.QPushButton(self.frame_8)
        self.highPassNotch.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.highPassNotch.setFont(font)
        self.highPassNotch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.highPassNotch.setObjectName("highPassNotch")
        self.gridLayout_6.addWidget(self.highPassNotch, 3, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_8, 2, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_3)
        self.frame_9.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(3000, 3000))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(316, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setMinimumSize(QtCore.QSize(220, 0))
        self.label_8.setMaximumSize(QtCore.QSize(220, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.frecSegundoOrden = QtWidgets.QLineEdit(self.frame_9)
        self.frecSegundoOrden.setEnabled(True)
        self.frecSegundoOrden.setMinimumSize(QtCore.QSize(220, 0))
        self.frecSegundoOrden.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frecSegundoOrden.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.frecSegundoOrden.setInputMask("")
        self.frecSegundoOrden.setText("")
        self.frecSegundoOrden.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.frecSegundoOrden.setClearButtonEnabled(True)
        self.frecSegundoOrden.setObjectName("frecSegundoOrden")
        self.horizontalLayout_3.addWidget(self.frecSegundoOrden)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setMinimumSize(QtCore.QSize(220, 0))
        self.label_9.setMaximumSize(QtCore.QSize(220, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.xsi = QtWidgets.QLineEdit(self.frame_9)
        self.xsi.setMinimumSize(QtCore.QSize(220, 0))
        self.xsi.setMaximumSize(QtCore.QSize(220, 16777215))
        self.xsi.setClearButtonEnabled(True)
        self.xsi.setObjectName("xsi")
        self.horizontalLayout_5.addWidget(self.xsi)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setMinimumSize(QtCore.QSize(220, 0))
        self.label_7.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.gananciaSegundoOrden = QtWidgets.QLineEdit(self.frame_9)
        self.gananciaSegundoOrden.setMinimumSize(QtCore.QSize(220, 0))
        self.gananciaSegundoOrden.setMaximumSize(QtCore.QSize(220, 16777215))
        self.gananciaSegundoOrden.setClearButtonEnabled(True)
        self.gananciaSegundoOrden.setObjectName("gananciaSegundoOrden")
        self.horizontalLayout_6.addWidget(self.gananciaSegundoOrden)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setMinimumSize(QtCore.QSize(220, 0))
        self.label_5.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.omegaz = QtWidgets.QLineEdit(self.frame_9)
        self.omegaz.setMinimumSize(QtCore.QSize(220, 0))
        self.omegaz.setMaximumSize(QtCore.QSize(220, 16777215))
        self.omegaz.setClearButtonEnabled(True)
        self.omegaz.setObjectName("omegaz")
        self.horizontalLayout_12.addWidget(self.omegaz)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setMinimumSize(QtCore.QSize(220, 0))
        self.label_6.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.xsiz = QtWidgets.QLineEdit(self.frame_9)
        self.xsiz.setMinimumSize(QtCore.QSize(220, 0))
        self.xsiz.setMaximumSize(QtCore.QSize(220, 16777215))
        self.xsiz.setClearButtonEnabled(True)
        self.xsiz.setObjectName("xsiz")
        self.horizontalLayout_13.addWidget(self.xsiz)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.gridLayout_10.addLayout(self.verticalLayout_7, 0, 1, 3, 1)
        spacerItem5 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(245, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(316, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_9, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_3, 0, 0, 1, 1)
        self.mainMenu.addWidget(self.segundoOrdenMenu)
        self.graficosMenu = QtWidgets.QWidget()
        self.graficosMenu.setObjectName("graficosMenu")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.graficosMenu)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_11 = QtWidgets.QFrame(self.graficosMenu)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_11.setPalette(palette)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(2)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        spacerItem8 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.eje_x = QtWidgets.QComboBox(self.frame_11)
        self.eje_x.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 44, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        self.eje_x.setPalette(palette)
        self.eje_x.setObjectName("eje_x")
        self.eje_x.addItem("")
        self.eje_x.addItem("")
        self.horizontalLayout_8.addWidget(self.eje_x)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        spacerItem9 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.eje_y = QtWidgets.QComboBox(self.frame_11)
        self.eje_y.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.eje_y.setPalette(palette)
        self.eje_y.setObjectName("eje_y")
        self.eje_y.addItem("")
        self.eje_y.addItem("")
        self.horizontalLayout_9.addWidget(self.eje_y)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.graficarBode = QtWidgets.QPushButton(self.frame_11)
        self.graficarBode.setMinimumSize(QtCore.QSize(75, 50))
        self.graficarBode.setMaximumSize(QtCore.QSize(75, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.graficarBode.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.graficarBode.setFont(font)
        self.graficarBode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graficarBode.setObjectName("graficarBode")
        self.horizontalLayout_10.addWidget(self.graficarBode)
        self.gridLayout_13.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_11, 2, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.graficosMenu)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 149, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 149, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(202, 149, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 56, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 42, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_10.setPalette(palette)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(2)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_17.addWidget(self.label_12, 0, 0, 1, 3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.entrada = QtWidgets.QComboBox(self.frame_10)
        self.entrada.setMinimumSize(QtCore.QSize(100, 0))
        self.entrada.setObjectName("entrada")
        self.entrada.addItem("")
        self.entrada.addItem("")
        self.entrada.addItem("")
        self.horizontalLayout_7.addWidget(self.entrada)
        self.gridLayout_17.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.graficarSalida = QtWidgets.QPushButton(self.frame_10)
        self.graficarSalida.setMinimumSize(QtCore.QSize(0, 50))
        self.graficarSalida.setMaximumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.graficarSalida.setFont(font)
        self.graficarSalida.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.graficarSalida.setObjectName("graficarSalida")
        self.gridLayout_17.addWidget(self.graficarSalida, 2, 2, 1, 1)
        self.dependeDeEntrada = QtWidgets.QStackedWidget(self.frame_10)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        gradient = QtGui.QRadialGradient(0.5, 0.5, 0.5, 0.5, 0.5)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.1, QtGui.QColor(255, 255, 255))
        gradient.setColorAt(0.2, QtGui.QColor(255, 176, 176, 167))
        gradient.setColorAt(0.3, QtGui.QColor(255, 151, 151, 92))
        gradient.setColorAt(0.4, QtGui.QColor(255, 125, 125, 51))
        gradient.setColorAt(0.5, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.52, QtGui.QColor(255, 76, 76, 205))
        gradient.setColorAt(0.6, QtGui.QColor(255, 180, 180, 84))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255, 0))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.dependeDeEntrada.setPalette(palette)
        self.dependeDeEntrada.setObjectName("dependeDeEntrada")
        self.senoideElegida = QtWidgets.QWidget()
        self.senoideElegida.setObjectName("senoideElegida")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.senoideElegida)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frecEntradaSen = QtWidgets.QLineEdit(self.senoideElegida)
        self.frecEntradaSen.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frecEntradaSen.setClearButtonEnabled(True)
        self.frecEntradaSen.setObjectName("frecEntradaSen")
        self.verticalLayout_10.addWidget(self.frecEntradaSen)
        self.ampEntradaSen = QtWidgets.QLineEdit(self.senoideElegida)
        self.ampEntradaSen.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ampEntradaSen.setClearButtonEnabled(True)
        self.ampEntradaSen.setObjectName("ampEntradaSen")
        self.verticalLayout_10.addWidget(self.ampEntradaSen)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.gridLayout_15.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.dependeDeEntrada.addWidget(self.senoideElegida)
        self.escalonUnitarioElegido = QtWidgets.QWidget()
        self.escalonUnitarioElegido.setObjectName("escalonUnitarioElegido")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.escalonUnitarioElegido)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ampEntradaEscalon = QtWidgets.QLineEdit(self.escalonUnitarioElegido)
        self.ampEntradaEscalon.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ampEntradaEscalon.setClearButtonEnabled(True)
        self.ampEntradaEscalon.setObjectName("ampEntradaEscalon")
        self.gridLayout_16.addWidget(self.ampEntradaEscalon, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem12, 0, 1, 1, 1)
        self.dependeDeEntrada.addWidget(self.escalonUnitarioElegido)
        self.pulsoPeriodicoElegido = QtWidgets.QWidget()
        self.pulsoPeriodicoElegido.setObjectName("pulsoPeriodicoElegido")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pulsoPeriodicoElegido)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ampEntradaPulso = QtWidgets.QLineEdit(self.pulsoPeriodicoElegido)
        self.ampEntradaPulso.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ampEntradaPulso.setClearButtonEnabled(True)
        self.ampEntradaPulso.setObjectName("ampEntradaPulso")
        self.gridLayout_12.addWidget(self.ampEntradaPulso, 0, 0, 1, 1)
        self.dutyCycle = QtWidgets.QLineEdit(self.pulsoPeriodicoElegido)
        self.dutyCycle.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dutyCycle.setClearButtonEnabled(True)
        self.dutyCycle.setObjectName("dutyCycle")
        self.gridLayout_12.addWidget(self.dutyCycle, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 1, 1, 1, 1)
        self.frecEntradaPulso = QtWidgets.QLineEdit(self.pulsoPeriodicoElegido)
        self.frecEntradaPulso.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frecEntradaPulso.setClearButtonEnabled(True)
        self.frecEntradaPulso.setObjectName("frecEntradaPulso")
        self.gridLayout_12.addWidget(self.frecEntradaPulso, 2, 0, 1, 1)
        self.dependeDeEntrada.addWidget(self.pulsoPeriodicoElegido)
        self.gridLayout_17.addWidget(self.dependeDeEntrada, 1, 1, 1, 1)
        self.gridLayout_14.addWidget(self.frame_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.graficosMenu)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(25)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_14.addWidget(self.label_11, 0, 0, 1, 1)
        self.mainMenu.addWidget(self.graficosMenu)
        self.gridLayout_2.addWidget(self.mainMenu, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        #####validator#####
        self.validator = QDoubleValidator(self)
        self.frecPrimerOrden.setValidator(self.validator)
        self.gananciaPrimerOrden.setValidator(self.validator)
        self.frecSegundoOrden.setValidator(self.validator)
        self.gananciaSegundoOrden.setValidator(self.validator)
        self.ampEntradaSen.setValidator(self.validator)
        self.frecEntradaSen.setValidator(self.validator)
        self.xsi.setValidator(self.validator)
        self.omegaz.setValidator(self.validator)
        self.xsiz.setValidator(self.validator)
        self.ampEntradaEscalon.setValidator(self.validator)
        self.ampEntradaPulso.setValidator(self.validator)
        self.frecEntradaPulso.setValidator(self.validator)
        self.dutyCycle.setValidator(self.validator)

        self.retranslateUi(MainWindow)
        self.mainMenu.setCurrentIndex(0)
        self.dependeDeEntrada.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Seleccione el orden del </span></p><p><span style=\" font-size:24pt;\">filtro a utilizar:</span></p></body></html>"))
        self.primerOrden.setText(_translate("MainWindow", "Primer Orden"))
        self.segundoOrden.setText(_translate("MainWindow", "Segundo Orden"))
        self.label_2.setText(_translate("MainWindow", "Filtros de Primer Orden:"))
        self.label_4.setText(_translate("MainWindow", "Ingrese la frecuencia del polo/cero:    "))
        self.frecPrimerOrden.setPlaceholderText(_translate("MainWindow", "Ej: 50Hz"))
        self.label_10.setText(_translate("MainWindow", "                         Ganancia en veces:  "))
        self.pasaAltosPrimerOrden.setText(_translate("MainWindow", "Pasa Altos"))
        self.pasaBajosPrimerOrden.setText(_translate("MainWindow", "Pasa Bajos"))
        self.pasaTodoPrimerOrden.setText(_translate("MainWindow", "Pasa Todo"))
        self.label_3.setText(_translate("MainWindow", "Filtros de Segundo Orden:"))
        self.pasaAltosSegundoOrden.setText(_translate("MainWindow", "Pasa Altos"))
        self.pasaBajosSegundoOrden.setText(_translate("MainWindow", "Pasa Bajos"))
        self.pasaBanda.setText(_translate("MainWindow", "Pasa Banda"))
        self.pasaTodoSegundoOrden.setText(_translate("MainWindow", "Pasa Todo"))
        self.lowPassNotch.setText(_translate("MainWindow", "Low-pass Notch"))
        self.notch.setText(_translate("MainWindow", "Notch"))
        self.highPassNotch.setText(_translate("MainWindow", "High-pass Notch"))
        self.label_8.setText(_translate("MainWindow", "            Ingrese la frecuencia del polo/cero: "))
        self.frecSegundoOrden.setPlaceholderText(_translate("MainWindow", "En Hz, Ej: 50"))
        self.label_9.setText(_translate("MainWindow", "Ingrese el  coeficiente de amortiguamiento:   "))
        self.xsi.setPlaceholderText(_translate("MainWindow", "Ej: 0.8"))
        self.label_7.setText(_translate("MainWindow", "                                     Ganancia en veces:"))
        self.label_5.setText(_translate("MainWindow", "                                                 Ingrese ωz:  "))
        self.label_6.setText(_translate("MainWindow", "                                                  Ingrese ξz:  "))
        self.label_15.setText(_translate("MainWindow", "Eje x:"))
        self.eje_x.setItemText(0, _translate("MainWindow", "Hz"))
        self.eje_x.setItemText(1, _translate("MainWindow", "rad/s"))
        self.label_16.setText(_translate("MainWindow", "Eje y:"))
        self.eje_y.setItemText(0, _translate("MainWindow", "dBs"))
        self.eje_y.setItemText(1, _translate("MainWindow", "Veces"))
        self.graficarBode.setText(_translate("MainWindow", "Graficar"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Bode:</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">Salida del sistema:</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Entrada:"))
        self.entrada.setItemText(0, _translate("MainWindow", "Senoide"))
        self.entrada.setItemText(1, _translate("MainWindow", "Escalon unitario"))
        self.entrada.setItemText(2, _translate("MainWindow", "Pulso periódico"))
        self.graficarSalida.setText(_translate("MainWindow", "Graficar"))
        self.frecEntradaSen.setPlaceholderText(_translate("MainWindow", "Frecuencia"))
        self.ampEntradaSen.setPlaceholderText(_translate("MainWindow", "Amplitud"))
        self.ampEntradaEscalon.setPlaceholderText(_translate("MainWindow", "Amplitud"))
        self.ampEntradaPulso.setPlaceholderText(_translate("MainWindow", "Amplitud"))
        self.dutyCycle.setPlaceholderText(_translate("MainWindow", "Duty Cycle"))
        self.frecEntradaPulso.setPlaceholderText(_translate("MainWindow", "Frecuencia"))
        self.label_11.setText(_translate("MainWindow", "Seleccione una opción a graficar:"))

import returnIcon.returnIcon
